import { ErpItem, OcrInvoiceData } from './types';

export const SAMPLE_OCR_INVOICES: Record<string, OcrInvoiceData> = {
  hikvision: {
    supplier: 'Prama Hikvision India Pvt Ltd',
    invoiceNumber: 'HKV/26-27/0894',
    date: '2026-09-25',
    gstin: '27AADCP8912K1Z5',
    items: [
      {
        product: 'Camera',
        brand: 'Hikvision',
        model: 'DS-2CD1023G0E-I (2MP IP Bullet)',
        quantity: 10,
        rate: 1650,
        discount: 500,
        gstPercent: 18,
        total: 18880,
        serialNumbers: ['HKV-2609-901', 'HKV-2609-902', 'HKV-2609-903', 'HKV-2609-904', 'HKV-2609-905'],
      },
      {
        product: 'NVR',
        brand: 'Hikvision',
        model: 'DS-7608NI-Q1/8P (8Ch PoE NVR)',
        quantity: 2,
        rate: 5400,
        discount: 108,
        gstPercent: 18,
        total: 12620,
        serialNumbers: ['NVR-HK-8821', 'NVR-HK-8822'],
      },
    ],
    grandTotal: 31500,
  },
  cpplus: {
    supplier: 'Aditya Infotech Ltd (CP Plus)',
    invoiceNumber: 'CPP/DEL/4419',
    date: '2026-09-25',
    gstin: '07AAACA5512F1Z9',
    items: [
      {
        product: 'Camera',
        brand: 'CP Plus',
        model: 'CP-UNC-DA21PL3 (2.4MP IR Dome)',
        quantity: 12,
        rate: 1350,
        discount: 400,
        gstPercent: 18,
        total: 18644,
        serialNumbers: ['CPP-DM-1101', 'CPP-DM-1102', 'CPP-DM-1103', 'CPP-DM-1104'],
      },
      {
        product: 'HDD',
        brand: 'WD Purple',
        model: 'WD42PURZ 4TB Surveillance HDD',
        quantity: 3,
        rate: 6200,
        discount: 300,
        gstPercent: 18,
        total: 21594,
        serialNumbers: ['WDP-4TB-771', 'WDP-4TB-772', 'WDP-4TB-773'],
      },
      {
        product: 'Cable',
        brand: 'D-Link',
        model: 'NCB-C6UGRYR-305 (305m CAT6 Box)',
        quantity: 2,
        rate: 4800,
        discount: 100,
        gstPercent: 18,
        total: 11210,
        serialNumbers: ['CAT6-DL-301', 'CAT6-DL-302'],
      },
    ],
    grandTotal: 51448,
  },
};

export const INITIAL_ERP_ITEMS: ErpItem[] = [
  // ================= CUSTOMERS =================
  {
    id: 'cust_sharma',
    ownerId: 'demo_owner',
    category: 'customer',
    code: 'CUST-001',
    title: 'Sharma Traders',
    subtitle: 'Commercial Warehouse & Retail Hub',
    partyName: 'Rajesh Sharma',
    mobile: '9810456789',
    location: 'Plot 14, Okhla Industrial Area Phase-II, New Delhi',
    gstin: '07AABCS1429B1Z1',
    status: 'Active',
    priority: 'High',
    quantity: 14,
    minQuantity: 0,
    rate: 0,
    amount: 148500,     // Total billed
    paidAmount: 106000, // Total paid (Outstanding: 42,500)
    taxAmount: 22650,
    discountAmount: 3000,
    dateStr: '2026-09-12',
    endDateStr: '2027-09-12',
    assignedTo: 'Ravi Kumar',
    notes: '8 IP Cameras + 8Ch PoE NVR + 4TB HDD installed. Annual AMC active.',
    tags: ['VIP Commercial', 'AMC Active', '8-Cam IP Setup'],
  },
  {
    id: 'cust_apex',
    ownerId: 'demo_owner',
    category: 'customer',
    code: 'CUST-002',
    title: 'Apex Hospital & Diagnostics',
    subtitle: 'Multi-Floor Healthcare Facility (32 Cameras)',
    partyName: 'Dr. Arvind Mehta',
    mobile: '9811229988',
    location: 'Sector 18, Noida, UP',
    gstin: '09AABCA9921C1Z4',
    status: 'Active',
    priority: 'High',
    quantity: 36,
    minQuantity: 0,
    rate: 0,
    amount: 385000,
    paidAmount: 240000, // Outstanding: 1,45,000
    taxAmount: 58700,
    discountAmount: 5000,
    dateStr: '2026-08-20',
    endDateStr: '2027-08-20',
    assignedTo: 'Ravi Kumar',
    notes: '32Ch NVR Rack setup with biometric entry & PTZ perimeter cameras.',
    tags: ['Hospital', 'AMC Active', '32Ch Setup'],
  },
  {
    id: 'cust_rajput',
    ownerId: 'demo_owner',
    category: 'customer',
    code: 'CUST-003',
    title: 'Rajput Jewellers Showroom',
    subtitle: 'High-Security Vault & Showroom Audio-Video CCTV',
    partyName: 'Vikram Singh Rajput',
    mobile: '9873344556',
    location: 'Karol Bagh Main Market, New Delhi',
    gstin: '07AAACR4410M1Z8',
    status: 'Active',
    priority: 'High',
    quantity: 18,
    minQuantity: 0,
    rate: 0,
    amount: 265000,
    paidAmount: 152500, // Outstanding: 1,12,500
    taxAmount: 40420,
    discountAmount: 2500,
    dateStr: '2026-09-02',
    endDateStr: '2027-09-02',
    assignedTo: 'Vikas Verma',
    notes: 'ColorVu 4MP Two-Way Audio Cameras + Dual 8TB RAID NVR.',
    tags: ['Jewellery Vault', 'ColorVu 4K', 'Cloud Backup'],
  },
  {
    id: 'cust_metro',
    ownerId: 'demo_owner',
    category: 'customer',
    code: 'CUST-004',
    title: 'Metro Heights RWA Society',
    subtitle: 'Gated Residential Towers & Boom Barrier ANPR',
    partyName: 'Col. R.K. Khanna (Secretary)',
    mobile: '9910088776',
    location: 'Dwarka Sector 12, New Delhi',
    gstin: '07AAATM7721P1Z2',
    status: 'Active',
    priority: 'Medium',
    quantity: 48,
    minQuantity: 0,
    rate: 0,
    amount: 490000,
    paidAmount: 365000, // Outstanding: 1,25,000
    taxAmount: 74745,
    discountAmount: 8000,
    dateStr: '2026-07-15',
    endDateStr: '2027-07-15',
    assignedTo: 'Ravi Kumar',
    notes: 'Tower lobbies, lifts, and main gate ANPR license plate recognition cameras.',
    tags: ['RWA Society', 'ANPR Gate', 'Fiber Backbone'],
  },

  // ================= CCTV EQUIPMENT / SITE ASSET REGISTRY (Section 7) =================
  {
    id: 'eq_sharma_cam1',
    ownerId: 'demo_owner',
    category: 'equipment',
    code: 'ABC123',
    title: 'Camera 1 — Hikvision XYZ',
    subtitle: 'Hikvision DS-2CD1023G0E-I (2MP IP Bullet)',
    partyName: 'Sharma Traders',
    mobile: '9810456789',
    location: 'Main Gate',
    gstin: 'INV-2026-104',
    status: 'Active',
    priority: 'Normal',
    quantity: 1,
    minQuantity: 0,
    rate: 2500,
    amount: 2500,
    paidAmount: 2500,
    taxAmount: 450,
    discountAmount: 0,
    dateStr: '2026-09-12',
    endDateStr: '2027-09-12',
    assignedTo: 'Ravi Kumar',
    notes: 'Purchase: 05/09/2026 | Sale: 11/09/2026 | Installed: 12/09/2026 | Outdoor Weatherproof IP67',
    tags: ['Serial: ABC123', 'Main Gate', 'Warranty: Active'],
  },
  {
    id: 'eq_sharma_cam2',
    ownerId: 'demo_owner',
    category: 'equipment',
    code: 'ABC124',
    title: 'Camera 2 — Hikvision XYZ',
    subtitle: 'Hikvision DS-2CD1123G0E-I (2MP IP Dome)',
    partyName: 'Sharma Traders',
    mobile: '9810456789',
    location: 'Office',
    gstin: 'INV-2026-104',
    status: 'Active',
    priority: 'Normal',
    quantity: 1,
    minQuantity: 0,
    rate: 2500,
    amount: 2500,
    paidAmount: 2500,
    taxAmount: 450,
    discountAmount: 0,
    dateStr: '2026-09-12',
    endDateStr: '2027-09-12',
    assignedTo: 'Ravi Kumar',
    notes: 'Purchase: 05/09/2026 | Sale: 11/09/2026 | Installed: 12/09/2026 | MD Cabin Audio Dome',
    tags: ['Serial: ABC124', 'Office', 'Warranty: Active'],
  },
  {
    id: 'eq_sharma_cam4',
    ownerId: 'demo_owner',
    category: 'equipment',
    code: 'ABC126',
    title: 'Camera 4 — Hikvision XYZ',
    subtitle: 'Hikvision DS-2CD1023G0E-I (2MP IP Bullet)',
    partyName: 'Sharma Traders',
    mobile: '9810456789',
    location: 'Loading Bay 2',
    gstin: 'INV-2026-104',
    status: 'Service Required',
    priority: 'High',
    quantity: 1,
    minQuantity: 0,
    rate: 2500,
    amount: 2500,
    paidAmount: 2500,
    taxAmount: 450,
    discountAmount: 0,
    dateStr: '2026-09-12',
    endDateStr: '2027-09-12',
    assignedTo: 'Ravi Kumar',
    notes: 'Purchase: 05/09/2026 | Installed: 12/09/2026 | Reported RJ45 PoE power drop on 25/09/2026',
    tags: ['Serial: ABC126', 'Loading Bay 2', 'Warranty: Active'],
  },
  {
    id: 'eq_sharma_nvr',
    ownerId: 'demo_owner',
    category: 'equipment',
    code: 'NVR12345',
    title: 'NVR — Hikvision 8Ch PoE NVR',
    subtitle: 'Hikvision DS-7608NI-Q1/8P',
    partyName: 'Sharma Traders',
    mobile: '9810456789',
    location: 'Server Rack (Ground Floor)',
    gstin: 'INV-2026-104',
    status: 'Active',
    priority: 'Normal',
    quantity: 1,
    minQuantity: 0,
    rate: 8500,
    amount: 8500,
    paidAmount: 8500,
    taxAmount: 1530,
    discountAmount: 0,
    dateStr: '2026-09-12',
    endDateStr: '2027-09-12',
    assignedTo: 'Ravi Kumar',
    notes: 'Purchase: 05/09/2026 | Installed: 12/09/2026 | Firmware v4.72 Hik-Connect Online',
    tags: ['Serial: NVR12345', 'Server Room', 'Warranty: Active'],
  },
  {
    id: 'eq_sharma_hdd',
    ownerId: 'demo_owner',
    category: 'equipment',
    code: 'HDD98765',
    title: 'HDD — WD Purple 4TB Surveillance',
    subtitle: 'Western Digital WD42PURZ 4TB 24x7',
    partyName: 'Sharma Traders',
    mobile: '9810456789',
    location: 'Inside NVR12345',
    gstin: 'INV-2026-104',
    status: 'Expiring Soon',
    priority: 'Medium',
    quantity: 1,
    minQuantity: 0,
    rate: 5500,
    amount: 5500,
    paidAmount: 5500,
    taxAmount: 990,
    discountAmount: 0,
    dateStr: '2024-10-10',
    endDateStr: '2026-10-10',
    assignedTo: 'Ravi Kumar',
    notes: '⚠ Warranty Expiring Soon (15 days left). S.M.A.R.T Health: 98% Normal.',
    tags: ['Serial: HDD98765', 'WD Purple', 'Expiring Soon'],
  },

  // ================= STOCK / INVENTORY MANAGEMENT (Section 8) =================
  {
    id: 'stk_cam_hik2mp',
    ownerId: 'demo_owner',
    category: 'stock',
    code: 'SKU-CAM-001',
    title: 'Hikvision 2MP IP NightVision Bullet',
    subtitle: 'Camera | Brand: Hikvision | Model: DS-2CD1023G0E-I',
    partyName: 'Prama Hikvision India Pvt Ltd',
    mobile: '18',
    location: 'Rack A-01',
    gstin: 'Camera',
    status: 'In Stock',
    priority: 'Normal',
    quantity: 42,
    minQuantity: 15,
    rate: 1650,     // Purchase Rate
    amount: 2500,   // Sale Rate
    paidAmount: 0,
    taxAmount: 18,  // GST %
    discountAmount: 0,
    dateStr: '2026-09-25',
    endDateStr: '',
    assignedTo: 'Suresh Yadav',
    notes: '30m IR PoE Bullet Camera IP67',
    tags: ['HKV-2609-01', 'HKV-2609-02', 'HKV-2609-03', 'HKV-2609-04'],
  },
  {
    id: 'stk_nvr_8ch',
    ownerId: 'demo_owner',
    category: 'stock',
    code: 'SKU-NVR-008',
    title: 'Hikvision 8-Channel 4K PoE NVR',
    subtitle: 'NVR | Brand: Hikvision | Model: DS-7608NI-Q1/8P',
    partyName: 'Prama Hikvision India Pvt Ltd',
    mobile: '18',
    location: 'Rack B-02',
    gstin: 'NVR',
    status: 'In Stock',
    priority: 'Normal',
    quantity: 11,
    minQuantity: 5,
    rate: 5400,
    amount: 8500,
    paidAmount: 0,
    taxAmount: 18,
    discountAmount: 0,
    dateStr: '2026-09-25',
    endDateStr: '',
    assignedTo: 'Suresh Yadav',
    notes: 'Built-in 8 PoE Interfaces, H.265+, 1 SATA up to 8TB',
    tags: ['NVR-7608-101', 'NVR-7608-102', 'NVR-7608-103'],
  },
  {
    id: 'stk_dvr_8ch',
    ownerId: 'demo_owner',
    category: 'stock',
    code: 'SKU-DVR-004',
    title: 'CP Plus 8Ch Full-HD Cosmic HD DVR',
    subtitle: 'DVR | Brand: CP Plus | Model: CP-UVR-0801E1-CS',
    partyName: 'Aditya Infotech Ltd (CP Plus)',
    mobile: '18',
    location: 'Rack B-04',
    gstin: 'DVR',
    status: 'In Stock',
    priority: 'Normal',
    quantity: 16,
    minQuantity: 6,
    rate: 2850,
    amount: 4400,
    paidAmount: 0,
    taxAmount: 18,
    discountAmount: 0,
    dateStr: '2026-09-20',
    endDateStr: '',
    assignedTo: 'Suresh Yadav',
    notes: 'Supports CVI/AHD/TVI/CVBS/IP auto-adaptive input',
    tags: ['CPP-DVR-501', 'CPP-DVR-502'],
  },
  {
    id: 'stk_hdd_4tb',
    ownerId: 'demo_owner',
    category: 'stock',
    code: 'SKU-HDD-4TB',
    title: 'WD Purple 4TB Surveillance Hard Drive',
    subtitle: 'HDD | Brand: Western Digital | Model: WD42PURZ',
    partyName: 'Aditya Infotech Ltd (CP Plus)',
    mobile: '18',
    location: 'Safe Locker S-1',
    gstin: 'HDD',
    status: 'Low Stock',
    priority: 'High',
    quantity: 4,
    minQuantity: 10,
    rate: 4200,
    amount: 5500,
    paidAmount: 0,
    taxAmount: 18,
    discountAmount: 0,
    dateStr: '2026-09-25',
    endDateStr: '',
    assignedTo: 'Suresh Yadav',
    notes: 'AllFrame 4K technology, 3-Year Manufacturer Warranty',
    tags: ['WDP-9801', 'WDP-9802', 'WDP-9803', 'WDP-9804'],
  },
  {
    id: 'stk_cable_cat6',
    ownerId: 'demo_owner',
    category: 'stock',
    code: 'SKU-CBL-CAT6',
    title: 'D-Link 305m CAT6 Pure Copper Roll',
    subtitle: 'Cable | Brand: D-Link | Model: NCB-C6UGRYR-305',
    partyName: 'SecureTech Surveillance Wholesale',
    mobile: '18',
    location: 'Bay C-01',
    gstin: 'Cable',
    status: 'Low Stock',
    priority: 'High',
    quantity: 3,
    minQuantity: 8,
    rate: 4600,
    amount: 6200,
    paidAmount: 0,
    taxAmount: 18,
    discountAmount: 0,
    dateStr: '2026-09-22',
    endDateStr: '',
    assignedTo: 'Suresh Yadav',
    notes: '23 AWG Solid Bare Copper for PoE long-distance runs',
    tags: ['DL-C6-881', 'DL-C6-882', 'DL-C6-883'],
  },
  {
    id: 'stk_smps_8ch',
    ownerId: 'demo_owner',
    category: 'stock',
    code: 'SKU-SMP-08',
    title: 'ERD 12V 10A 8-Channel CCTV Power Supply',
    subtitle: 'SMPS | Brand: ERD | Model: SMPS-12V10A-8CH',
    partyName: 'SecureTech Surveillance Wholesale',
    mobile: '18',
    location: 'Rack D-01',
    gstin: 'SMPS',
    status: 'In Stock',
    priority: 'Normal',
    quantity: 28,
    minQuantity: 10,
    rate: 520,
    amount: 950,
    paidAmount: 0,
    taxAmount: 18,
    discountAmount: 0,
    dateStr: '2026-09-18',
    endDateStr: '',
    assignedTo: 'Suresh Yadav',
    notes: 'Individual PTC Resettable Fuse with Surge Protection',
    tags: ['ERD-SMPS-11', 'ERD-SMPS-12'],
  },
  {
    id: 'stk_poe_8p',
    ownerId: 'demo_owner',
    category: 'stock',
    code: 'SKU-POE-08',
    title: 'TP-Link 8-Port Gigabit PoE+ Switch (2 Uplink)',
    subtitle: 'POE Switch | Brand: TP-Link | Model: TL-SG1008MP',
    partyName: 'SecureTech Surveillance Wholesale',
    mobile: '18',
    location: 'Rack B-06',
    gstin: 'POE Switch',
    status: 'Low Stock',
    priority: 'High',
    quantity: 2,
    minQuantity: 6,
    rate: 3100,
    amount: 4500,
    paidAmount: 0,
    taxAmount: 18,
    discountAmount: 0,
    dateStr: '2026-09-19',
    endDateStr: '',
    assignedTo: 'Suresh Yadav',
    notes: '250m Extend Mode for IP Cameras + Priority Video QoS',
    tags: ['TPL-POE-401', 'TPL-POE-402'],
  },
  {
    id: 'stk_bnc_pack',
    ownerId: 'demo_owner',
    category: 'stock',
    code: 'SKU-BNC-50',
    title: 'Pure Brass Screw-Type BNC & DC Connector Pack (50 Pcs)',
    subtitle: 'BNC | Brand: Varah Pro | Model: BNC-BRASS-50',
    partyName: 'SecureTech Surveillance Wholesale',
    mobile: '18',
    location: 'Bin E-03',
    gstin: 'BNC',
    status: 'In Stock',
    priority: 'Normal',
    quantity: 45,
    minQuantity: 15,
    rate: 350,
    amount: 650,
    paidAmount: 0,
    taxAmount: 18,
    discountAmount: 0,
    dateStr: '2026-09-15',
    endDateStr: '',
    assignedTo: 'Suresh Yadav',
    notes: 'Heavy duty copper core BNC + Moulded DC Wire',
    tags: ['BATCH-BNC-2609'],
  },
  {
    id: 'stk_rack_4u',
    ownerId: 'demo_owner',
    category: 'stock',
    code: 'SKU-RCK-4U',
    title: '4U Wall Mount Loaded Network DVR/NVR Rack',
    subtitle: 'Rack | Brand: Netrack | Model: NR-4U-WM-GLASS',
    partyName: 'SecureTech Surveillance Wholesale',
    mobile: '18',
    location: 'Bay C-04',
    gstin: 'Rack',
    status: 'Low Stock',
    priority: 'Medium',
    quantity: 3,
    minQuantity: 5,
    rate: 1450,
    amount: 2400,
    paidAmount: 0,
    taxAmount: 18,
    discountAmount: 0,
    dateStr: '2026-09-14',
    endDateStr: '',
    assignedTo: 'Suresh Yadav',
    notes: 'Includes Cooling Fan, 6-Socket PDU, Cantilever Tray & Lock',
    tags: ['RCK-4U-01', 'RCK-4U-02', 'RCK-4U-03'],
  },

  // ================= SUPPLIERS =================
  {
    id: 'sup_hikvision',
    ownerId: 'demo_owner',
    category: 'supplier',
    code: 'SUP-001',
    title: 'Prama Hikvision India Pvt Ltd',
    subtitle: 'Authorized National Distributor — IP & TurboHD',
    partyName: 'Sandeep Kulkarni (RM)',
    mobile: '9820112233',
    location: 'Nehru Place Commercial Tower, New Delhi',
    gstin: '27AADCP8912K1Z5',
    status: 'Active',
    priority: 'High',
    quantity: 18,
    minQuantity: 0,
    rate: 0,
    amount: 645000,
    paidAmount: 520000, // Payable: 1,25,000
    taxAmount: 98389,
    discountAmount: 12000,
    dateStr: '2026-09-25',
    endDateStr: '',
    assignedTo: 'Priya Nair',
    notes: '30-Day Credit Terms | Direct RMA Replacement Counter',
    tags: ['Hikvision', 'NVR', 'IP Cameras'],
  },
  {
    id: 'sup_cpplus',
    ownerId: 'demo_owner',
    category: 'supplier',
    code: 'SUP-002',
    title: 'Aditya Infotech Ltd (CP Plus)',
    subtitle: 'Regional Stockist — Cameras, DVR & WD Purple HDD',
    partyName: 'Manish Gupta',
    mobile: '9811445566',
    location: 'Okhla Phase-I, New Delhi',
    gstin: '07AAACA5512F1Z9',
    status: 'Active',
    priority: 'Normal',
    quantity: 12,
    minQuantity: 0,
    rate: 0,
    amount: 410000,
    paidAmount: 355000, // Payable: 55,000
    taxAmount: 62542,
    discountAmount: 6500,
    dateStr: '2026-09-20',
    endDateStr: '',
    assignedTo: 'Priya Nair',
    notes: 'WD Purple HDD + CP Plus Analog/IP Range',
    tags: ['CP Plus', 'WD Purple', 'D-Link'],
  },

  // ================= PURCHASE INVOICES (Section 4) =================
  {
    id: 'pur_today_01',
    ownerId: 'demo_owner',
    category: 'purchase',
    code: 'HKV/26-27/0894',
    title: 'Prama Hikvision India Pvt Ltd',
    subtitle: '10x Hikvision 2MP Bullet + 2x 8Ch PoE NVR (OCR Verified)',
    partyName: 'Prama Hikvision India Pvt Ltd',
    mobile: '9820112233',
    location: 'Warehouse Inward Gate-1',
    gstin: '27AADCP8912K1Z5',
    status: 'Stock Updated',
    priority: 'Normal',
    quantity: 12,
    minQuantity: 0,
    rate: 26695,
    amount: 31500, // Matches Admin Dashboard Today Purchase ₹31,500
    paidAmount: 31500,
    taxAmount: 4805,
    discountAmount: 608,
    dateStr: '2026-09-25',
    endDateStr: '',
    assignedTo: 'Suresh Yadav',
    notes: 'OCR Scanned & Verified by Admin. Stock increased automatically (+10 Cameras, +2 NVRs).',
    tags: ['OCR Verified', 'HKV-2609-901', 'NVR-HK-8821'],
  },

  // ================= SALES INVOICES (Section 5) =================
  {
    id: 'sale_today_01',
    ownerId: 'demo_owner',
    category: 'sale',
    code: 'INV-2026-104',
    title: 'Sharma Traders',
    subtitle: '8x Hikvision 2MP IP Camera + 1x 8Ch NVR + 1x 4TB HDD + Installation',
    partyName: 'Sharma Traders',
    mobile: '9810456789',
    location: 'Plot 14, Okhla Industrial Area Phase-II, New Delhi',
    gstin: '07AABCS1429B1Z1',
    status: 'Partially Paid',
    priority: 'High',
    quantity: 10,
    minQuantity: 0,
    rate: 34000,
    amount: 42500,
    paidAmount: 30000,
    taxAmount: 6480,
    discountAmount: 3000, // Installation Charges stored here
    dateStr: '2026-09-25',
    endDateStr: '2027-09-25',
    assignedTo: 'Ravi Kumar',
    notes: 'Camera 8 × ₹2,500 (₹20,000) | NVR 1 × ₹8,500 | HDD 1 × ₹5,500 | Installation ₹3,000 | GST 18%',
    tags: ['8x Camera', '1x 8Ch NVR', '1x 4TB HDD', 'Installation'],
  },
  {
    id: 'sale_today_02',
    ownerId: 'demo_owner',
    category: 'sale',
    code: 'INV-2026-105',
    title: 'Rajput Jewellers Showroom',
    subtitle: '6x ColorVu 4MP Audio Camera + 1x 8Ch NVR + 4U Rack + Cabling',
    partyName: 'Rajput Jewellers Showroom',
    mobile: '9873344556',
    location: 'Karol Bagh Main Market, New Delhi',
    gstin: '07AAACR4410M1Z8',
    status: 'Paid',
    priority: 'High',
    quantity: 8,
    minQuantity: 0,
    rate: 36440,
    amount: 43000, // Together with INV-2026-104 (42,500 + 43,000 = ₹85,500 Today Sales!)
    paidAmount: 32000,
    taxAmount: 6560,
    discountAmount: 2500,
    dateStr: '2026-09-25',
    endDateStr: '2027-09-25',
    assignedTo: 'Vikas Verma',
    notes: 'Full showroom upgrade with mic recording and Hik-Connect mobile setup.',
    tags: ['6x ColorVu 4MP', '1x NVR', '1x 4U Rack'],
  },

  // ================= QUOTATIONS (Section 18) =================
  {
    id: 'quot_sharma_01',
    ownerId: 'demo_owner',
    category: 'quotation',
    code: 'QTN-2026-042',
    title: 'Sharma Traders — Phase 2 Warehouse Expansion',
    subtitle: 'Camera 8 × ₹2,500 | NVR 1 × ₹8,500 | HDD 1 × ₹5,500 | Installation ₹3,000',
    partyName: 'Sharma Traders',
    mobile: '9810456789',
    location: 'Plot 14, Okhla Industrial Area Phase-II, New Delhi',
    gstin: '07AABCS1429B1Z1',
    status: 'Approved',
    priority: 'High',
    quantity: 10,
    minQuantity: 0,
    rate: 37000,
    amount: 42500,
    paidAmount: 0,
    taxAmount: 6480,
    discountAmount: 980,
    dateStr: '2026-09-24',
    endDateStr: '2026-10-08',
    assignedTo: 'Amit Patel',
    notes: 'Camera 8 × ₹2,500 = ₹20,000 | NVR 1 × ₹8,500 | HDD 1 × ₹5,500 | Installation ₹3,000 | GST ₹6,480 | Discount ₹980',
    tags: ['Camera 8x2500', 'NVR 1x8500', 'HDD 1x5500', 'Install 3000'],
  },
  {
    id: 'quot_sunrise_02',
    ownerId: 'demo_owner',
    category: 'quotation',
    code: 'QTN-2026-043',
    title: 'Sunrise Public School — Campus & Bus Bay CCTV',
    subtitle: '16x IP Cameras + 16Ch NVR + 2x 4TB HDD + 2x PoE Switch',
    partyName: 'Sunrise Public School',
    mobile: '9818776655',
    location: 'Vasant Kunj, New Delhi',
    gstin: '07AAATS3312E1Z1',
    status: 'Pending Approval',
    priority: 'Medium',
    quantity: 21,
    minQuantity: 0,
    rate: 72000,
    amount: 84960,
    paidAmount: 0,
    taxAmount: 12960,
    discountAmount: 2000,
    dateStr: '2026-09-25',
    endDateStr: '2026-10-10',
    assignedTo: 'Amit Patel',
    notes: 'Sent PDF on WhatsApp to Principal Office. Follow-up scheduled.',
    tags: ['16x Camera', '16Ch NVR', '2x 4TB HDD', 'CBSE Compliance'],
  },

  // ================= INSTALLATIONS (Sections 11 & 12) =================
  {
    id: 'inst_sharma_01',
    ownerId: 'demo_owner',
    category: 'installation',
    code: 'JOB-INST-101',
    title: '8 Camera Installation',
    subtitle: 'Items: 8 Camera, 1 NVR, 1 HDD, Cable (180m CAT6), 8Ch SMPS',
    partyName: 'Sharma Traders',
    mobile: '9810456789',
    location: 'Plot 14, Okhla Industrial Area Phase-II, New Delhi',
    gstin: 'INV-2026-104',
    status: 'In Progress',
    priority: 'High',
    quantity: 8,
    minQuantity: 0,
    rate: 3000,
    amount: 42500,
    paidAmount: 30000,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25',
    endDateStr: '',
    assignedTo: 'Ravi Kumar',
    notes: 'Main Gate, Office Cabin, Loading Bay 1 & 2, Dispatch Area. GPS Verified: 28.5355° N, 77.2711° E',
    tags: ['8 Camera', '1 NVR', '1 HDD', 'Cable', 'SMPS'],
  },
  {
    id: 'inst_rajput_02',
    ownerId: 'demo_owner',
    category: 'installation',
    code: 'JOB-INST-102',
    title: '6 ColorVu 4K Vault & Showroom Setup',
    subtitle: 'Items: 6 ColorVu Camera, 1 NVR, 1 4U Rack, 1 PoE Switch',
    partyName: 'Rajput Jewellers Showroom',
    mobile: '9873344556',
    location: 'Karol Bagh Main Market, New Delhi',
    gstin: 'INV-2026-105',
    status: 'Assigned',
    priority: 'High',
    quantity: 6,
    minQuantity: 0,
    rate: 2500,
    amount: 43000,
    paidAmount: 32000,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25',
    endDateStr: '',
    assignedTo: 'Vikas Verma',
    notes: 'Two-way audio calibration required at main billing counter.',
    tags: ['6 ColorVu', '1 NVR', '4U Rack', 'PoE Switch'],
  },
  {
    id: 'inst_apex_03',
    ownerId: 'demo_owner',
    category: 'installation',
    code: 'JOB-INST-103',
    title: '4 ICU Corridor Dome Camera Addition',
    subtitle: 'Items: 4 IP Dome Camera, 1 PoE Switch, 90m CAT6 Cable',
    partyName: 'Apex Hospital & Diagnostics',
    mobile: '9811229988',
    location: 'Sector 18, Noida, UP',
    gstin: 'INV-2026-098',
    status: 'Pending',
    priority: 'Medium',
    quantity: 4,
    minQuantity: 0,
    rate: 2000,
    amount: 18500,
    paidAmount: 10000,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-26',
    endDateStr: '',
    assignedTo: 'Ravi Kumar',
    notes: 'Silent drilling required between 2 PM and 5 PM.',
    tags: ['4 Dome Cam', '1 PoE Switch', 'CAT6 Cable'],
  },

  // ================= SERVICE CALLS / COMPLAINTS (Sections 13 & 14) =================
  {
    id: 'srv_sharma_cam4',
    ownerId: 'demo_owner',
    category: 'service',
    code: 'SRV-2026-401',
    title: 'Camera 4 Not Working',
    subtitle: 'No Video / PoE Link Loss on Channel 4 (Loading Bay 2)',
    partyName: 'Sharma Traders',
    mobile: '9810456789',
    location: 'Plot 14, Okhla Industrial Area Phase-II, New Delhi',
    gstin: 'ABC126',
    status: 'Assigned',
    priority: 'High',
    quantity: 1,
    minQuantity: 0,
    rate: 500,
    amount: 650,
    paidAmount: 0,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25 10:15 AM',
    endDateStr: '',
    assignedTo: 'Ravi Kumar',
    notes: 'Check RJ45 Waterproof Connector & 12V PoE Splitter at Loading Bay 2.',
    tags: ['Camera 4', 'PoE Connector', 'High Priority'],
  },
  {
    id: 'srv_metro_dvr',
    ownerId: 'demo_owner',
    category: 'service',
    code: 'SRV-2026-402',
    title: 'NVR Continuous Beeping (HDD Error)',
    subtitle: 'Tower B Guard Room NVR beeping alert — S.M.A.R.T check needed',
    partyName: 'Metro Heights RWA Society',
    mobile: '9910088776',
    location: 'Dwarka Sector 12, New Delhi',
    gstin: 'NVR-MH-02',
    status: 'On Way',
    priority: 'High',
    quantity: 1,
    minQuantity: 0,
    rate: 800,
    amount: 800,
    paidAmount: 0,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25 11:30 AM',
    endDateStr: '',
    assignedTo: 'Ravi Kumar',
    notes: 'Carry spare SATA cable and 12V 5A Adapter + replacement 4TB WD Purple HDD.',
    tags: ['HDD Beep', 'SATA Cable', 'AMC Visit'],
  },
  {
    id: 'srv_apex_app',
    ownerId: 'demo_owner',
    category: 'service',
    code: 'SRV-2026-403',
    title: 'Hik-Connect Mobile View Offline after Router Change',
    subtitle: 'Reconfigure DHCP & DNS on 32Ch NVR after Airtel Fiber upgrade',
    partyName: 'Apex Hospital & Diagnostics',
    mobile: '9811229988',
    location: 'Sector 18, Noida, UP',
    gstin: 'NVR-APX-01',
    status: 'Completed',
    priority: 'Medium',
    quantity: 1,
    minQuantity: 0,
    rate: 500,
    amount: 500,
    paidAmount: 500,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-24 04:20 PM',
    endDateStr: '2026-09-24 05:10 PM',
    assignedTo: 'Vikas Verma',
    notes: 'Updated Static IP 192.168.1.200 & DNS 8.8.8.8. Signed by Dr. Arvind Mehta.',
    tags: ['Network Config', 'Hik-Connect', 'Signed'],
  },

  // ================= STAFF MANAGEMENT (Section 9) =================
  {
    id: 'stf_ravi',
    ownerId: 'demo_owner',
    category: 'staff',
    code: 'EMP-001',
    title: 'Ravi Kumar',
    subtitle: 'Technician',
    partyName: 'Ravi Kumar',
    mobile: '9811223344',
    location: 'Okhla Field Zone, New Delhi',
    gstin: 'AADHAAR-VERIFIED',
    status: 'Active',
    priority: 'High',
    quantity: 26, // Days present this month
    minQuantity: 0,
    rate: 24000,  // Monthly Salary
    amount: 24000,
    paidAmount: 24000,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2024-03-10',
    endDateStr: '',
    assignedTo: 'Deepak Singh',
    notes: 'Senior IP & Fiber CCTV Technician. Aadhar, Driving License & Police Verification on file.',
    tags: ['Technician', 'IP Specialist', 'GPS Verified'],
  },
  {
    id: 'stf_vikas',
    ownerId: 'demo_owner',
    category: 'staff',
    code: 'EMP-002',
    title: 'Vikas Verma',
    subtitle: 'Installer',
    partyName: 'Vikas Verma',
    mobile: '9811556677',
    location: 'Karol Bagh & West Delhi Zone',
    gstin: 'AADHAAR-VERIFIED',
    status: 'Active',
    priority: 'Normal',
    quantity: 25,
    minQuantity: 0,
    rate: 19500,
    amount: 19500,
    paidAmount: 19500,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2024-07-01',
    endDateStr: '',
    assignedTo: 'Deepak Singh',
    notes: 'Conduit piping, rack dressing, and outdoor bullet installation specialist.',
    tags: ['Installer', 'Cabling', 'Rack Dressing'],
  },
  {
    id: 'stf_priya',
    ownerId: 'demo_owner',
    category: 'staff',
    code: 'EMP-003',
    title: 'Priya Nair',
    subtitle: 'Accountant',
    partyName: 'Priya Nair',
    mobile: '9822334455',
    location: 'Head Office — Nehru Place',
    gstin: 'PAN-VERIFIED',
    status: 'Active',
    priority: 'Normal',
    quantity: 26,
    minQuantity: 0,
    rate: 28000,
    amount: 28000,
    paidAmount: 28000,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2023-11-15',
    endDateStr: '',
    assignedTo: 'Admin',
    notes: 'Handles GST Billing, Collections, Cash/Bank Reconciliation & Supplier Ledger.',
    tags: ['Accountant', 'GST Filing', 'Accounts'],
  },
  {
    id: 'stf_amit',
    ownerId: 'demo_owner',
    category: 'staff',
    code: 'EMP-004',
    title: 'Amit Patel',
    subtitle: 'Sales',
    partyName: 'Amit Patel',
    mobile: '9899112233',
    location: 'Delhi NCR Corporate Sales',
    gstin: 'PAN-VERIFIED',
    status: 'Active',
    priority: 'Normal',
    quantity: 24,
    minQuantity: 0,
    rate: 25000,
    amount: 25000,
    paidAmount: 25000,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2024-01-20',
    endDateStr: '',
    assignedTo: 'Admin',
    notes: 'Site surveys, BOQ Quotations, and AMC renewals.',
    tags: ['Sales', 'Site Survey', 'Quotations'],
  },
  {
    id: 'stf_suresh',
    ownerId: 'demo_owner',
    category: 'staff',
    code: 'EMP-005',
    title: 'Suresh Yadav',
    subtitle: 'Store Manager',
    partyName: 'Suresh Yadav',
    mobile: '9871234560',
    location: 'Central Godown — Okhla',
    gstin: 'AADHAAR-VERIFIED',
    status: 'Active',
    priority: 'Normal',
    quantity: 26,
    minQuantity: 0,
    rate: 22000,
    amount: 22000,
    paidAmount: 22000,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2024-02-10',
    endDateStr: '',
    assignedTo: 'Admin',
    notes: 'Serial barcode scanning, inward OCR verification & technician kit dispatch.',
    tags: ['Store Manager', 'Inventory', 'Serial Tracking'],
  },
  {
    id: 'stf_deepak',
    ownerId: 'demo_owner',
    category: 'staff',
    code: 'EMP-006',
    title: 'Deepak Singh',
    subtitle: 'Service Manager',
    partyName: 'Deepak Singh',
    mobile: '9810998877',
    location: 'Head Office — Service Desk',
    gstin: 'PAN-VERIFIED',
    status: 'Active',
    priority: 'High',
    quantity: 26,
    minQuantity: 0,
    rate: 30000,
    amount: 30000,
    paidAmount: 30000,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2023-06-01',
    endDateStr: '',
    assignedTo: 'Admin',
    notes: 'Assigns installations, SLA tracking for service calls & warranty RMA claims.',
    tags: ['Service Manager', 'Dispatch', 'SLA'],
  },

  // ================= GPS + SELFIE ATTENDANCE (Section 10) =================
  {
    id: 'att_ravi_today',
    ownerId: 'demo_owner',
    category: 'attendance',
    code: 'ATT-20260925-01',
    title: 'Ravi Kumar',
    subtitle: 'Technician | Check-In: 09:32 AM',
    partyName: 'Ravi Kumar',
    mobile: '9811223344',
    location: 'Sharma Traders Site, Okhla Phase-II (28.5355° N, 77.2711° E)',
    gstin: 'GPS-VERIFIED',
    status: 'Checked In',
    priority: 'Normal',
    quantity: 1,
    minQuantity: 0,
    rate: 0,
    amount: 0,
    paidAmount: 0,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25 09:32 AM',
    endDateStr: 'On Field',
    assignedTo: 'Ravi Kumar',
    notes: 'Selfie Verified with Helmet & Tool Kit at Customer Gate.',
    tags: ['Selfie Verified', 'GPS: 28.5355, 77.2711', 'On Time'],
  },
  {
    id: 'att_vikas_today',
    ownerId: 'demo_owner',
    category: 'attendance',
    code: 'ATT-20260925-02',
    title: 'Vikas Verma',
    subtitle: 'Installer | Check-In: 09:45 AM',
    partyName: 'Vikas Verma',
    mobile: '9811556677',
    location: 'Karol Bagh Main Market (28.6514° N, 77.1907° E)',
    gstin: 'GPS-VERIFIED',
    status: 'Checked In',
    priority: 'Normal',
    quantity: 1,
    minQuantity: 0,
    rate: 0,
    amount: 0,
    paidAmount: 0,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25 09:45 AM',
    endDateStr: 'On Field',
    assignedTo: 'Vikas Verma',
    notes: 'Reached Rajput Jewellers site for 6-Camera installation.',
    tags: ['Selfie Verified', 'GPS: 28.6514, 77.1907', 'On Time'],
  },

  // ================= PAYMENTS / RECEIPTS (Section 15) =================
  {
    id: 'pay_today_01',
    ownerId: 'demo_owner',
    category: 'payment',
    code: 'RCPT-2026-801',
    title: 'Sharma Traders',
    subtitle: 'UPI | Ref: UPI-626918442910',
    partyName: 'Sharma Traders',
    mobile: '9810456789',
    location: 'INV-2026-104',
    gstin: 'UPI',
    status: 'Received',
    priority: 'Normal',
    quantity: 1,
    minQuantity: 0,
    rate: 30000,
    amount: 30000,
    paidAmount: 30000,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25',
    endDateStr: '',
    assignedTo: 'Ravi Kumar',
    notes: 'Advance payment collected on site against 8-Camera Installation Invoice INV-2026-104.',
    tags: ['UPI', 'INV-2026-104', 'Receipt Sent'],
  },
  {
    id: 'pay_today_02',
    ownerId: 'demo_owner',
    category: 'payment',
    code: 'RCPT-2026-802',
    title: 'Rajput Jewellers Showroom',
    subtitle: 'Bank NEFT | Ref: HDFC26092599182',
    partyName: 'Rajput Jewellers Showroom',
    mobile: '9873344556',
    location: 'INV-2026-105',
    gstin: 'Bank',
    status: 'Received',
    priority: 'Normal',
    quantity: 1,
    minQuantity: 0,
    rate: 32000,
    amount: 32000, // 30,000 + 32,000 = ₹62,000 Today Collection!
    paidAmount: 32000,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25',
    endDateStr: '',
    assignedTo: 'Priya Nair',
    notes: 'NEFT settled in HDFC Current Account against INV-2026-105.',
    tags: ['Bank', 'INV-2026-105', 'Verified'],
  },

  // ================= EXPENSES (Section 17) =================
  {
    id: 'exp_today_01',
    ownerId: 'demo_owner',
    category: 'expense',
    code: 'EXP-2026-301',
    title: 'Field Bike Petrol & Toll — Okhla & Noida Runs',
    subtitle: 'Petrol | Paid via UPI',
    partyName: 'Ravi Kumar',
    mobile: '9811223344',
    location: 'IndianOil Fuel Station, Okhla',
    gstin: 'Petrol',
    status: 'Approved',
    priority: 'Normal',
    quantity: 1,
    minQuantity: 0,
    rate: 1200,
    amount: 1200,
    paidAmount: 1200,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25',
    endDateStr: '',
    assignedTo: 'Ravi Kumar',
    notes: 'Fuel bill photo attached. Approved by Service Manager.',
    tags: ['Petrol', 'Bill Attached'],
  },
  {
    id: 'exp_today_02',
    ownerId: 'demo_owner',
    category: 'expense',
    code: 'EXP-2026-302',
    title: 'Bosch SDS Hammer Drill Bits & RJ45 Crimping Tool',
    subtitle: 'Tools | Paid via Cash',
    partyName: 'Vikas Verma',
    mobile: '9811556677',
    location: 'Karol Bagh Hardware Store',
    gstin: 'Tools',
    status: 'Approved',
    priority: 'Normal',
    quantity: 1,
    minQuantity: 0,
    rate: 2800,
    amount: 2800,
    paidAmount: 2800,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25',
    endDateStr: '',
    assignedTo: 'Vikas Verma',
    notes: 'Heavy duty concrete drill bits for wall conduit entry.',
    tags: ['Tools', 'Cash'],
  },
  {
    id: 'exp_today_03',
    ownerId: 'demo_owner',
    category: 'expense',
    code: 'EXP-2026-303',
    title: 'Showroom Electricity & Fiber Internet Bill',
    subtitle: 'Electricity | Paid via Bank',
    partyName: 'BSES Rajdhani Power',
    mobile: '',
    location: 'Head Office — Nehru Place',
    gstin: 'Electricity',
    status: 'Approved',
    priority: 'Normal',
    quantity: 1,
    minQuantity: 0,
    rate: 4500,
    amount: 4500, // 1,200 + 2,800 + 4,500 = ₹8,500 Today Expenses!
    paidAmount: 4500,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25',
    endDateStr: '',
    assignedTo: 'Priya Nair',
    notes: 'Monthly office utility bill paid online.',
    tags: ['Electricity', 'Office'],
  },

  // ================= AMC MANAGEMENT (Section 20) =================
  {
    id: 'amc_sharma',
    ownerId: 'demo_owner',
    category: 'amc',
    code: 'AMC-2026-01',
    title: 'Sharma Traders — Comprehensive 8-Camera AMC',
    subtitle: 'Covered: 8 IP Cameras, 1 PoE NVR, 1 4TB HDD, Cabling',
    partyName: 'Sharma Traders',
    mobile: '9810456789',
    location: 'Plot 14, Okhla Phase-II, New Delhi',
    gstin: 'Paid',
    status: 'Active',
    priority: 'High',
    quantity: 4,    // Total Yearly Visits
    minQuantity: 1, // Completed Visits
    rate: 8000,
    amount: 8000,
    paidAmount: 8000,
    taxAmount: 1440,
    discountAmount: 0,
    dateStr: '2026-09-12',
    endDateStr: '2027-09-11',
    assignedTo: 'Ravi Kumar',
    notes: 'Next Preventive Visit: 12/12/2026 | Lens cleaning, NVR health check & backup verification.',
    tags: ['Next Visit: 12/12/2026', '4 Visits/Yr', 'Paid'],
  },
  {
    id: 'amc_apex',
    ownerId: 'demo_owner',
    category: 'amc',
    code: 'AMC-2026-02',
    title: 'Apex Hospital — 32-Camera Priority SLA AMC',
    subtitle: 'Covered: 32 IP Cameras, 2 NVRs, 4 PoE Switches, Rack',
    partyName: 'Apex Hospital & Diagnostics',
    mobile: '9811229988',
    location: 'Sector 18, Noida, UP',
    gstin: 'Paid',
    status: 'Visit Due Soon',
    priority: 'High',
    quantity: 12,   // Monthly visits
    minQuantity: 3, // Completed
    rate: 36000,
    amount: 36000,
    paidAmount: 36000,
    taxAmount: 6480,
    discountAmount: 0,
    dateStr: '2026-06-01',
    endDateStr: '2027-05-31',
    assignedTo: 'Ravi Kumar',
    notes: 'Next Visit Due: 01/10/2026 | Monthly hospital ICU & Reception NVR audit.',
    tags: ['Next Visit: 01/10/2026', '12 Visits/Yr', 'SLA 4-Hr'],
  },
  {
    id: 'amc_metro',
    ownerId: 'demo_owner',
    category: 'amc',
    code: 'AMC-2026-03',
    title: 'Metro Heights RWA — 48-Camera & Boom Barrier AMC',
    subtitle: 'Covered: 48 Cameras, ANPR Gate Camera, Fiber Media Converters',
    partyName: 'Metro Heights RWA Society',
    mobile: '9910088776',
    location: 'Dwarka Sector 12, New Delhi',
    gstin: 'Pending',
    status: 'Renewal Due',
    priority: 'High',
    quantity: 6,
    minQuantity: 5,
    rate: 45000,
    amount: 45000,
    paidAmount: 25000,
    taxAmount: 8100,
    discountAmount: 0,
    dateStr: '2025-10-05',
    endDateStr: '2026-10-04',
    assignedTo: 'Amit Patel',
    notes: 'Next Visit: 30/09/2026 | Balance ₹20,000 pending before renewal.',
    tags: ['Next Visit: 30/09/2026', 'Payment Pending', '48 Cameras'],
  },

  // ================= CASH & BANK LEDGER (Section 16) =================
  {
    id: 'cb_cash_opening',
    ownerId: 'demo_owner',
    category: 'cash_bank',
    code: 'CSH-OPEN-01',
    title: 'Cash Drawer Opening Balance',
    subtitle: 'Cash | Head Office Locker',
    partyName: 'Office Cash Drawer',
    mobile: '',
    location: 'Cash',
    gstin: 'Opening',
    status: 'Verified',
    priority: 'Normal',
    quantity: 1,
    minQuantity: 0,
    rate: 48500,
    amount: 48500,
    paidAmount: 48500,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25',
    endDateStr: '',
    assignedTo: 'Priya Nair',
    notes: 'Physical cash verified at 09:00 AM.',
    tags: ['Cash', 'Opening Balance'],
  },
  {
    id: 'cb_bank_hdfc',
    ownerId: 'demo_owner',
    category: 'cash_bank',
    code: 'BNK-HDFC-01',
    title: 'HDFC Bank Current A/C (••4829)',
    subtitle: 'Bank | Varah Management Enterprise Account',
    partyName: 'HDFC Bank Nehru Place',
    mobile: '',
    location: 'Bank',
    gstin: 'Opening',
    status: 'Verified',
    priority: 'Normal',
    quantity: 1,
    minQuantity: 0,
    rate: 385000,
    amount: 385000,
    paidAmount: 385000,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25',
    endDateStr: '',
    assignedTo: 'Priya Nair',
    notes: 'Primary GST business current account linked to UPI QR & NEFT.',
    tags: ['Bank', 'HDFC Current A/C'],
  },

  // ================= NOTIFICATION CENTER (Section 22) =================
  {
    id: 'notif_01',
    ownerId: 'demo_owner',
    category: 'notification',
    code: 'ALT-LOW-STK',
    title: '🔴 Low Stock Alert: WD Purple 4TB HDD & CAT6 Cable',
    subtitle: 'WD Purple 4TB has 4 units left (Min: 10). D-Link CAT6 has 3 boxes left.',
    partyName: 'Suresh Yadav',
    mobile: '',
    location: 'stock',
    gstin: 'red',
    status: 'Unread',
    priority: 'High',
    quantity: 4,
    minQuantity: 10,
    rate: 0,
    amount: 0,
    paidAmount: 0,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25 10:05 AM',
    endDateStr: '',
    assignedTo: 'Admin',
    notes: 'Reorder recommended from Aditya Infotech (CP Plus).',
    tags: ['Low Stock', 'Urgent'],
  },
  {
    id: 'notif_02',
    ownerId: 'demo_owner',
    category: 'notification',
    code: 'ALT-SRV-PND',
    title: '🟠 High-Priority Service Call: Sharma Traders',
    subtitle: 'Camera 4 Not Working at Loading Bay 2 — Assigned to Ravi Kumar',
    partyName: 'Sharma Traders',
    mobile: '9810456789',
    location: 'service',
    gstin: 'orange',
    status: 'Unread',
    priority: 'High',
    quantity: 1,
    minQuantity: 0,
    rate: 0,
    amount: 0,
    paidAmount: 0,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25 10:15 AM',
    endDateStr: '',
    assignedTo: 'Ravi Kumar',
    notes: 'Customer requested technician visit before 2:00 PM.',
    tags: ['Service Pending', 'Sharma Traders'],
  },
  {
    id: 'notif_03',
    ownerId: 'demo_owner',
    category: 'notification',
    code: 'ALT-PUR-OCR',
    title: '🔵 New Purchase Invoice Scanned via OCR',
    subtitle: 'Prama Hikvision Invoice HKV/26-27/0894 (₹31,500) verified & stock added.',
    partyName: 'Prama Hikvision India Pvt Ltd',
    mobile: '',
    location: 'purchase',
    gstin: 'blue',
    status: 'Read',
    priority: 'Normal',
    quantity: 12,
    minQuantity: 0,
    rate: 0,
    amount: 31500,
    paidAmount: 31500,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25 09:50 AM',
    endDateStr: '',
    assignedTo: 'Admin',
    notes: '+10 Cameras and +2 NVRs added to central stock.',
    tags: ['New Purchase', 'OCR'],
  },
  {
    id: 'notif_04',
    ownerId: 'demo_owner',
    category: 'notification',
    code: 'ALT-ATT-GPS',
    title: '🔵 Staff GPS Attendance: Ravi Kumar Checked In',
    subtitle: 'Ravi → 09:32 AM → Sharma Traders Site, Okhla Phase-II (Selfie + GPS Verified)',
    partyName: 'Ravi Kumar',
    mobile: '9811223344',
    location: 'attendance',
    gstin: 'blue',
    status: 'Read',
    priority: 'Normal',
    quantity: 1,
    minQuantity: 0,
    rate: 0,
    amount: 0,
    paidAmount: 0,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25 09:32 AM',
    endDateStr: '',
    assignedTo: 'Admin',
    notes: 'GPS Coordinates 28.5355° N, 77.2711° E verified.',
    tags: ['Staff Attendance', 'GPS'],
  },
  {
    id: 'notif_05',
    ownerId: 'demo_owner',
    category: 'notification',
    code: 'ALT-WRN-EXP',
    title: '🟠 Warranty Expiring Soon: WD Purple 4TB (HDD98765)',
    subtitle: 'Installed at Sharma Traders — Warranty ends on 10/10/2026',
    partyName: 'Sharma Traders',
    mobile: '9810456789',
    location: 'warranty',
    gstin: 'orange',
    status: 'Unread',
    priority: 'Medium',
    quantity: 1,
    minQuantity: 0,
    rate: 0,
    amount: 0,
    paidAmount: 0,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25 08:30 AM',
    endDateStr: '2026-10-10',
    assignedTo: 'Amit Patel',
    notes: 'Propose extended warranty or new HDD upgrade.',
    tags: ['Warranty Expiring', 'HDD98765'],
  },
  {
    id: 'notif_06',
    ownerId: 'demo_owner',
    category: 'notification',
    code: 'ALT-AMC-DUE',
    title: '🟠 AMC Visit Due: Apex Hospital & Diagnostics',
    subtitle: 'Monthly 32-Camera SLA preventive check due on 01/10/2026',
    partyName: 'Apex Hospital & Diagnostics',
    mobile: '9811229988',
    location: 'amc',
    gstin: 'orange',
    status: 'Unread',
    priority: 'High',
    quantity: 1,
    minQuantity: 0,
    rate: 0,
    amount: 36000,
    paidAmount: 36000,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-25 08:00 AM',
    endDateStr: '2026-10-01',
    assignedTo: 'Deepak Singh',
    notes: 'Assign technician for camera lens cleaning and NVR log check.',
    tags: ['AMC Due', 'Apex Hospital'],
  },
  {
    id: 'notif_07',
    ownerId: 'demo_owner',
    category: 'notification',
    code: 'ALT-JOB-CMP',
    title: '🟢 Job Completed: Apex Hospital Hik-Connect Reconfiguration',
    subtitle: 'Completed by Vikas Verma with customer digital signature.',
    partyName: 'Apex Hospital & Diagnostics',
    mobile: '9811229988',
    location: 'service',
    gstin: 'green',
    status: 'Read',
    priority: 'Normal',
    quantity: 1,
    minQuantity: 0,
    rate: 500,
    amount: 500,
    paidAmount: 500,
    taxAmount: 0,
    discountAmount: 0,
    dateStr: '2026-09-24 05:10 PM',
    endDateStr: '',
    assignedTo: 'Vikas Verma',
    notes: 'Service charge ₹500 collected.',
    tags: ['Job Completed', 'Service'],
  },
];
